/**
 * The Penpot side of the Design Phase: the Run's page, one board per screen,
 * and the board exports. Everything it runs is generated by penpotRender.ts.
 */
import type { ExportedImage, PenpotClient } from "@sdlc-code/clients";
import {
  CONNECTION_CHECK_CODE,
  ensurePageCode,
  screenCode,
} from "./penpotRender.js";
import type { DesignTokens, Screen } from "./uiSpec.js";

export type PenpotConnection = { file: string; page: string | null };
export type DrawnBoard = { boardId: string; name: string };

export type DrawScreenRequest = {
  pageName: string;
  /** Position of the board on the page, left to right. */
  index: number;
  screen: Screen;
  tokens: DesignTokens;
};

/** Draws a Run's screens in the Penpot Workspace File. */
export interface UiCanvas {
  /** Reads the connected file; throws PenpotError when no plugin is there. */
  checkConnection: () => Promise<PenpotConnection>;
  /** Opens the Run's page, creating it on the first Design Phase. */
  ensurePage: (
    pageName: string,
  ) => Promise<{ pageId: string; created: boolean }>;
  drawScreen: (request: DrawScreenRequest) => Promise<DrawnBoard>;
  exportBoard: (boardId: string) => Promise<ExportedImage>;
}

export class PenpotUiCanvas implements UiCanvas {
  #penpot: PenpotClient;

  constructor(penpot: PenpotClient) {
    this.#penpot = penpot;
  }

  checkConnection = (): Promise<PenpotConnection> =>
    this.#penpot.executeCode<PenpotConnection>(CONNECTION_CHECK_CODE);

  ensurePage = (
    pageName: string,
  ): Promise<{ pageId: string; created: boolean }> =>
    this.#penpot.executeCode(ensurePageCode(pageName));

  drawScreen = (request: DrawScreenRequest): Promise<DrawnBoard> =>
    this.#penpot.executeCode<DrawnBoard>(screenCode(request));

  exportBoard = (boardId: string): Promise<ExportedImage> =>
    this.#penpot.exportShape(boardId, "png");
}
