/**
 * The Penpot side of the Design Phase: the Run's page, one board per screen,
 * and the board exports. Everything it runs is generated by penpotRender.ts.
 */
import type { ExportedImage, PenpotClient } from "@sdlc-code/clients";
import {
  CONNECTION_CHECK_CODE,
  ensurePageCode,
  screenCode,
  sweepBoardsCode,
} from "./penpotRender.js";
import type { DesignTokens, Screen } from "./uiSpec.js";

/** The Penpot Workspace File the plugin is connected to. */
export type PenpotFileInfo = {
  file: string;
  fileId: string | null;
  page: string | null;
};

export type RunPage = {
  pageId: string;
  fileId: string | null;
  created: boolean;
};

export type DrawnBoard = { boardId: string; name: string };

export type DrawScreenRequest = {
  pageName: string;
  /** Position of the board on the page, left to right. */
  index: number;
  screen: Screen;
  tokens: DesignTokens;
};

/** Draws a Run's screens in the Penpot Workspace File. */
export interface UiCanvas {
  /** Reads the connected file; throws PenpotError when no plugin is there. */
  checkConnection: () => Promise<PenpotFileInfo>;
  /** Opens the Run's page, creating it on the first Design Phase. */
  ensurePage: (pageName: string) => Promise<RunPage>;
  drawScreen: (request: DrawScreenRequest) => Promise<DrawnBoard>;
  /** Removes boards of screens the design no longer has; returns their names. */
  sweepBoards: (pageName: string, keepScreens: string[]) => Promise<string[]>;
  exportBoard: (boardId: string) => Promise<ExportedImage>;
}

export class PenpotUiCanvas implements UiCanvas {
  #penpot: PenpotClient;

  constructor(penpot: PenpotClient) {
    this.#penpot = penpot;
  }

  checkConnection = (): Promise<PenpotFileInfo> =>
    this.#penpot.executeCode<PenpotFileInfo>(CONNECTION_CHECK_CODE);

  ensurePage = (pageName: string): Promise<RunPage> =>
    this.#penpot.executeCode<RunPage>(ensurePageCode(pageName));

  drawScreen = (request: DrawScreenRequest): Promise<DrawnBoard> =>
    this.#penpot.executeCode<DrawnBoard>(screenCode(request));

  sweepBoards = async (
    pageName: string,
    keepScreens: string[],
  ): Promise<string[]> => {
    const { removed } = await this.#penpot.executeCode<{ removed: string[] }>(
      sweepBoardsCode(pageName, keepScreens),
    );
    return removed;
  };

  exportBoard = (boardId: string): Promise<ExportedImage> =>
    this.#penpot.exportShape(boardId, "png");
}
